# Generated by Django 5.0.3 on 2024-05-10 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0002_jaminan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangGadai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_gadai', models.DateField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BarangGadai', to='nasabah.nasabah')),
            ],
        ),
    ]
