# Generated by Django 5.0.3 on 2024-05-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0003_baranggadai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasabah',
            name='saldo',
        ),
    ]
