# Generated by Django 5.0.3 on 2024-07-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0006_peminjaman_jaminan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='jaminan',
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='nasabah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Peminjaman', to='nasabah.nasabah'),
        ),
    ]
