# Generated by Django 5.0.3 on 2024-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0007_remove_peminjaman_jaminan_alter_peminjaman_nasabah'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='jumlah_pinjam',
            new_name='nilai',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='tanggal_pinjam',
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='deskripsi',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='nama_barang',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='tanggal_gadai',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='tanggal_jatuh_tempo',
            field=models.DateField(),
        ),
    ]
