# Generated by Django 5.0.3 on 2024-07-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0009_rename_nilai_peminjaman_jumlah_pinjam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='nasabah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjamans', to='nasabah.nasabah'),
        ),
    ]
