# Generated by Django 5.0.3 on 2024-07-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasabah', '0010_alter_peminjaman_nasabah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_pinjaman', models.DateField(auto_now_add=True)),
                ('tanggal_jatuh_tempo', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nasabah.jaminan')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nasabah.nasabah')),
            ],
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
    ]
