# Generated by Django 5.0.3 on 2024-05-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nasabah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaminan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal_pembaruan', models.DateField(auto_now=True)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nasabah.nasabah')),
            ],
        ),
    ]
